name = "crs-pulse-push"
main = "src/index.ts"
compatibility_date = "2024-11-01"

[[kv_namespaces]]
binding = "TOKENS_KV"
id = "588cfb0021b2409e9f5dc1083b0497e8"
preview_id = "51b5f45ff4034592bda05af1ebc4dfab"

[triggers]
crons = ["*/15 * * * *"]

# Optional: set via `wrangler secret put SYNC_SECRET` to protect POST /sync
# [vars]
# SYNC_SECRET = ""
